import type { NextPage } from 'next';
import Head from 'next/head';

import Home from '@components/Home';

const HomePage: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <Home />
  </>
);

export default HomePage;
